export const PRIVACY_POLICY_PATH = '/privacy';
export const TERMS_OF_SERVICES_PATH = '/terms';
export const COOKIE_POLICY_PATH = '/cookie';
export const SUCCESSFUL_CONFIRMATION = '/validation-success';
export const FAILED_CONFIRMATION = '/validation-fail';
export const CONFIRMATION_PATH = '/confirmation'
export const RECOVERY_PATH = '/recovery'
export const SUPPORT_LINK_PATH = '/settings?tab=help'
export const ALBUM_PATH = '/album'
export const ALBUMS_PATH = '/albums'
